### ISSUE TITLE
Missing some return statements in Sprite.cpp

### ISSUE THREAD

**Issue by dumbfingers** [CircuitMess/Platformio-Packages#1]
Hello,

Firstly thanks for building such a fun device, Nibble.

Recently I'm playing with Nibble on Visual Studio Code and found the below build error:

> lib/CircuitOS/src/Display/Sprite.cpp: In member function 'Sprite& Sprite::setTransparent(bool)':
> lib/CircuitOS/src/Display/Sprite.cpp:221:1: error: no return statement in function returning non-void [-Werror=return-type]
>   221 | }
>       | ^
> lib/CircuitOS/src/Display/Sprite.cpp: In member function 'Sprite& Sprite::setChroma(Color)':
> lib/CircuitOS/src/Display/Sprite.cpp:226:1: error: no return statement in function returning non-void [-Werror=return-type]
>   226 | }
>       | ^
> Compiling .pio/build/esp12e/lib2b0/CircuitOS/Loop/LoopManager.cpp.o
> Compiling .pio/build/esp12e/lib2b0/CircuitOS/Motion/MPU.cpp.o
> lib/CircuitOS/src/Display/Sprite.cpp: In member function 'Sprite& Sprite::resize(uint, uint)':
> lib/CircuitOS/src/Display/Sprite.cpp:214:5: error: control reaches end of non-void function [-Werror=return-type]
>   214 |  if(_created == false){
>       |     ^~~~~~~~
> Compiling .pio/build/esp12e/lib2b0/CircuitOS/Motion/MPUFusion.cpp.o
> cc1plus: some warnings being treated as errors
> *** [.pio/build/esp12e/lib2b0/CircuitOS/Display/Sprite.cpp.o] Error 1
> In file included from lib/CircuitOS/src/Input/Input.cpp:1:
> lib/CircuitOS/src/Input/Input.h: In constructor 'Input::Input(uint8_t)':
> lib/CircuitOS/src/Input/Input.h:95:24: warning: 'Input::btnHoldRepeatCounter' will be initialized after [-Wreorder]
>    95 |  std::vector<uint32_t> btnHoldRepeatCounter;
>       |                        ^~~~~~~~~~~~~~~~~~~~

It looks like some of the non-void functions are not getting return statements?

I'm using the latest platform libs from this repo, with latest PlatformIO on latest Visual Studio Code. Running on MacOS 11.4

**Comment by dumbfingers** [comment]
Update:

Tried with the sample hello world project here (and also please see the attached zip file)

https://circuitmess.com/resources/guides/en/platformio-nibble/simple-program-nibble

[Hello World.zip](https://github.com/CircuitMess/Platformio-Packages/files/6979063/Hello.World.zip)

And still getting the same error.

The same code builds & works when using CircuitBlocks.

**Comment by MiLeG** [comment]
@dumbfingers  Can you try placing this line in the platformio.ini file
 `build_flags = -w`
 
 This should suppress all the optional warnings that are turned on by default in platformIO, but the code is functional nonetheless.

**Comment by dumbfingers** [comment]
@MiLeG Hi Emil. Thanks for getting back. 
The error I had on build was:
`lib/CircuitOS/src/Display/Sprite.cpp:221:1: error: no return statement in function returning non-void [-Werror=return-type]
221 | }`

which seems an error from the lib?

I'll also try the build flags and report back. Thanks

**Comment by G-o-T-o** [comment]
Hello,

I had the very same issue compiling HelloWorld example in VSCode/PlatformIO  (getting the three compiler errors on missing return statement reported in the very first post by @dumbfingers.

Putting the additional line to platformio.ini file suggested by @MiLeG resolved the issue, so the compilation ended successfully.

Thanks for the support!

**Comment by MiLeG** [comment]
It would still be a good idea to take a look at the compilation warnings (treated as errors) since potential bugs could be hiding there, so we'll take a look at them when we have the time.

If you have the time, consider opening a pull request on our [CircuitOS](https://github.com/CircuitMess/CircuitOS) repo, that would help us a lot.
